name: Playwright Tests

on:
  workflow_dispatch:
   inputs:
      choice:
        type: choice
        description: Select the environment
        options:
        - Playwright Tests
                 
      OperatingSystem:
        type: choice
        description: select OS
        options:
        - Windows
        - 'OS X'
        
      OperatingSystemVersion:
        type: choice
        description: Select OS Version
        options:
        - '10'
        - Monterey     
        
      boolean:
        type: choice
        description: select browser
        options:
        - Chrome
        - Firefox
        - Safari

      name:
       type: choice
       description: Select Test case
       options:
        - All
        - example.spec.ts
        - example1.spec.ts
        
jobs:
  build:
    if: ${{ inputs.name == 'All' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
      
    - name: Install dependencies
      run: npm install
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps     
    - name: Run Playwright tests
      run: npx playwright test --reporter=junit --output=./test-results
    - name: Upload test results to GitHub Actions
      uses: actions/upload-artifact@v4
      with:
          name: playwright-test-results
          path: ./test-output/test-results.xml
          overwrite: true
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: test-results
        path: test-output/
        overwrite: true
        retention-days: 30
    
  
  build2:
    if: ${{ inputs.name != 'All' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
      
    - name: Install dependencies
      run: npm install
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps    
    - name: Run Playwright tests
      run: npx playwright test ${{ inputs.name }} --reporter=junit --output=./test-results
    - name: Upload test results to GitHub Actions
      uses: actions/upload-artifact@v4
      with:
          name: playwright-test-results
          path: ./test-output/test-results.xml
          overwrite: true
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: test-results
        path: test-output/
        overwrite: true
        retention-days: 30
    