name: Playwright Tests

on:
  workflow_dispatch:
   inputs:
      choice:
        type: choice
        description: Select the environment
        options:
        - https://qa.h-dnet.com/eventserv/dealereventadmin/events
                 
      OperatingSystem:
        type: choice
        description: select OS
        options:
        - Windows
        - 'OS X'
        
      OperatingSystemVersion:
        type: choice
        description: Select OS Version
        options:
        - '10'
        - Monterey     
        
      boolean:
        type: choice
        description: select browser
        options:
        - Chrome
        - Firefox
        - Safari

      name:
       type: choice
       description: Select Test case
       options:
        - All
        - example.spec.ts
        - test-1.spec.ts

jobs:
  build:
    if: ${{ inputs.name == 'All' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
      
    - name: Install dependencies
      run: npm install
        
    - name: Run Playwright tests
      run: npx playwright test --project=EventAdmin --retries=2
  
  build2:
    if: ${{ inputs.name != 'All' }}
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
      
    - name: Install dependencies
      run: npm install
        
    - name: Run Playwright tests
      run: npx playwright test ${{ inputs.name }} --project=EventAdmin
    # Run Playwright tests
    #- name: Run Playwright tests
    # run: npx playwright test
     
    # Run Maven build tasks
    # Cache Maven dependencies to speed up builds
    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Run Maven tests
    - name: Run tests with Maven
      run: mvn clean test

    # Upload test results to QMetry
    - name: Upload test results to QMetry
      run: |
        curl -X POST "https://your-qmetry-instance/api/v1/upload" \
          -H "Authorization: Bearer ${{ secrets.QMETRY_API_TOKEN}}" \
          -F "testResults=@target/surefire-reports/testng-results.xml" \
          -F "username=${{ secrets.QMETRY_USERNAME }}" \
          -F "password=${{ secrets.QMETRY_PASSWORD }}" \
          -F "testRunId=${{ secrets.QMETRY_TEST_RUN_ID }}"
      env:
        QMETRY_API_TOKEN: ${{ secrets.QMETRY_API_TOKEN }}
        QMETRY_USERNAME: ${{ secrets.QMETRY_USERNAME }}
        QMETRY_PASSWORD: ${{ secrets.QMETRY_PASSWORD }}
        QMETRY_TEST_RUN_ID: ${{ secrets.QMETRY_TEST_RUN_ID }}
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
